### PR TITLE
Revert "60-rebasing-the-testing-branch-be-ole-would-not-fix-the-not-resigned-the-old-updates-that-he-did-which-led-us-not-being-able-to-merge-it-with-main"

### PR DESCRIPTION
**Pull request by therealstrikeman**
Reverts therealstrikeman/godot#61

### CODE REVIEW

**Comment by therealstrikeman** [comment]
it wouldn't work and it cause me a headache

**Comment by therealstrikeman** [comment]
@OleMortensen8

**Comment by therealstrikeman** [comment]
so fix first testing branch and revert som of the changes

**Comment by OleMortensen8** [comment]
I don't see them.

**Pull request merged**
